# Perfil ativo — troque para 'prod' no servidor de produção
spring.profiles.active=dev

spring.application.name=snowflake-kafka-pipeline

# Exclui o autoconfigure do DataSource padrão do Spring
# porque o Snowflake usa um DataSource customizado via JDBC
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration