spring.profiles.active=dev

spring.application.name=snowflake-kafka-pipeline

# Desativa o autoconfigure do DataSource padrão do Spring
# Desativa o JPA/Hibernate completamente — usamos JdbcTemplate diretamente
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration